In [1]:
import numpy as np
ones = np.ones((3,4), dtype="int8")
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [2]:
ones[1, :]

array([1, 1, 1, 1], dtype=int8)

In [3]:
ones[1][:]

array([1, 1, 1, 1], dtype=int8)

In [4]:
ones?


In [6]:
np.random.normal(size=(4, 4))

array([[-0.28120228, -0.71591068,  0.83968467, -1.45720449],
       [-0.11810206,  0.6315932 , -2.74200182,  1.25149149],
       [ 0.11529313,  0.4840978 ,  1.08842621, -0.83403441],
       [ 2.14735696, -0.89428045, -0.46377764,  1.34466585]])

In [7]:
np.random.randint(1,10,size=(5,6))

array([[5, 1, 2, 4, 1, 4],
       [9, 5, 6, 1, 6, 9],
       [4, 8, 9, 2, 1, 2],
       [1, 1, 5, 6, 9, 2],
       [8, 2, 1, 4, 4, 2]])

In [11]:
a = np.random.randint(1,10,size=(5,6))
a.resize(2,15)
a

array([[8, 4, 5, 5, 8, 6, 1, 1, 4, 1, 7, 6, 7, 7, 6],
       [8, 5, 8, 9, 5, 8, 7, 6, 6, 7, 8, 8, 9, 4, 1]])